server:
  port: 8443

logging:
  level:
    gateway: debug

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/trgl-realm

  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/v1

        - id: product-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
          filters:
            - PrefixPath=/api/v1