server:
  port: 8443

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/targul

  cloud:
    gateway:
      routes:
        - id: get-route
          uri: http://localhost:8081
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/api/v1